#RESET
reset;
#LOAD THE MODEL
model direct.mod;
#CHANGE THE SOLVER (optional)
option solver cplex;
#SOLVE

solve;
#SHOW RESULTS
#display x_c,x_m;
#OTHER OPTIONS TO DISPLAY

show cel;#revenue, Aval_Time, Max_Mint, Max_Cinn;


display cel,P1,P2,P3;
display K1,K2,D1,D2,D3;
display b1,b2,bu;
display koszt_uwodornienia;
display koszt_obrobki_s1;
display S1,s11,s12,s13;
display S2,s21,s22,s23;
